# Generated by Django 3.2 on 2023-02-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0001_initial'),
        ('bar', '0002_auto_20230221_1542')
    ]

    operations = [
    ]
