# Generated by Django 3.2 on 2023-02-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
    ]
