# Generated by Django 3.2 on 2023-02-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20230221_1542'),
        ('foo', '0003_auto_20230221_1543'),
    ]

    operations = [
    ]
